export interface AlbumType {
    idArtist: string,
    idAlbum: string,
    strLabel: string,
    strArtist: string,
    strAlbumCDart: string,
    strAlbum: string,
    strAlbumThumb: string,
    intYearReleased: string,
    strGenre: string,
    strArtistStripped: string,
    strDescriptionEN: string,
    strAlbumBack: string,
    strAlbum3DThumb: string,
}
